# Use Dockerized infrastructure
sudo: false

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "frontend/spark-app/node_modules"
    - $HOME/.m2

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=tidal-repeater-254307
    - CLUSTER_NAME_PRD=mssl-cluster
    - CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a
    - FRONTEND_DOCKER_IMAGE_NAME=spark-frontend
    - BACKEND_DOCKER_IMAGE_NAME=spark-backend
    - FRONTEND_KUBE_DEPLOYMENT_NAME=spark-frontend
    - FRONTEND_KUBE_DEPLOYMENT_CONTAINER_NAME=spark-frontend
    - BACKEND_KUBE_DEPLOYMENT_NAME=spark-backend
    - BACKEND_KUBE_DEPLOYMENT_CONTAINER_NAME=spark-backend
    - FRONTEND_BUILD_DIR=./frontend/spark-app
    - BACKEND_BUILD_DIR=./restful-web-services
    - NODE_ENV=CI

matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      install:
        - cd frontend/spark-app
        - npm install
        - cd ../..
      script:
        - cd frontend/spark-app
        - npm test
        - CI=false npm run build
        - cd ../..

      deploy:

        - provider: script
          script: ./deploy-frontend-prod.sh
          skip-cleanup: true
          on:
            branch: develop

    - language: java
      dist: trusty
      jdk:
        - oraclejdk8
      install:
        - cd restful-web-services
        - ./install.config.sh
        - mvn clean package -Dmaven.javadoc.skip=true -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - cd ..
      script:
        - cd restful-web-services
        - mvn test
        - cd ..

      deploy:

        - provider: script
          script: ./deploy-backend-prod.sh
          skip-cleanup: true
          on:
            branch: develop

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash &> /dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

